sonar.projectKey=CheeziCrew_Swissgit
sonar.organization=cheezicrew

sonar.go.coverage.reportPaths=coverage.out
sonar.cpd.exclusions=**/*_test.go
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/exec.go
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=go:S4036
sonar.issue.ignore.multicriteria.e1.resourceKey=**/exec.go
