name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarqube:
    uses: CheeziCrew/.github/.github/workflows/sonarqube.yml@661562b6dbb576a9b339c05c58836307a5c22aae
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
