name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarqube:
    uses: CheeziCrew/.github/.github/workflows/sonarqube.yml@9c3630565cb23837cb9d60cfaf40e05950866108
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
