name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: CheeziCrew/.github/.github/workflows/dependabot-auto-merge.yml@bbc851eb23d97511231d2410f43d08857e343d2b
    secrets:
      APPROVE_TOKEN: ${{ secrets.APPROVE_TOKEN }}
