name: Release

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: CheeziCrew/.github/.github/workflows/release.yml@3bd54f3d4220a13f55689c035c4d4167a1e1e41b
